from . import fw_const
from . import fw_const
class DimmerConst(fw_const.DimmerConstBase):
    def __init__(self):
        fw_const.DimmerConstBase.__init__(self)
        self.is_complete = True
        self.VERSION = '2.2.x'
        self.attr = {
            'COMMAND_DEC_HW_TICKS': 0x86,
            'COMMAND_DEC_ZC_DELAY': 0x83,
            'COMMAND_DUMP_CHANNELS': 0xed,
            'COMMAND_DUMP_MEM': 0xee,
            'COMMAND_FADE': 0x11,
            'COMMAND_FORCE_TEMP_CHECK': 0x54,
            'COMMAND_GET_TIMER_TICKS': 0x52,
            'COMMAND_INCR_HW_TICKS': 0x85,
            'COMMAND_INCR_ZC_DELAY': 0x82,
            'COMMAND_INIT_EEPROM': 0x95,
            'COMMAND_MEASURE_FREQ': 0x94,
            'COMMAND_PRINT_CONFIG': 0x91,
            'COMMAND_PRINT_INFO': 0x53,
            'COMMAND_PRINT_METRICS': 0x55,
            'COMMAND_READ_AC_FREQUENCY': 0x23,
            'COMMAND_READ_CHANNELS': 0x12,
            'COMMAND_READ_INT_TEMP': 0x21,
            'COMMAND_READ_NTC': 0x20,
            'COMMAND_READ_VCC': 0x22,
            'COMMAND_RESTORE_FS': 0x51,
            'COMMAND_SET_LEVEL': 0x10,
            'COMMAND_SET_MODE': 0x56,
            'COMMAND_SET_ZC_DELAY': 0x84,
            'COMMAND_SET_ZC_SYNC': 0xec,
            'COMMAND_STATUS_ERROR': 0xff,
            'COMMAND_STATUS_OK': 0x00,
            'COMMAND_WRITE_CONFIG': 0x92,
            'COMMAND_WRITE_EEPROM': 0x50,
            'COMMAND_WRITE_EEPROM_NOW': 0x93,
            'COMMAND_ZC_TIMINGS_OUTPUT': 0x60,

            'EEPROM_FLAGS_CONFIG_UPDATED': 0x01,
            'EVENT_CHANNEL_ON_OFF': 0xf5,
            'EVENT_EEPROM_WRITTEN': 0xf3,
            'EVENT_FADING_COMPLETE': 0xf2,
            'EVENT_FREQUENCY_WARNING': 0xf4,
            'EVENT_METRICS_REPORT': 0xf0,
            'EVENT_SYNC_EVENT': 0xf6,
            'EVENT_TEMPERATURE_ALERT': 0xf1,

            'I2C_ADDRESS': 0x17,

            'OPTIONS_MODE_LEADING_EDGE': 0x02,
            'OPTIONS_NEGATIVE_ZC_DELAY': 0x08,
            'OPTIONS_RESTORE_LEVEL': 0x01,
            'OPTIONS_TEMP_ALERT_TRIGGERED': 0x04,

            'REGISTER_ADDRESS': 0xca,
            'REGISTER_ADJ_HW_CYCLES': 0xb1,
            'REGISTER_CH0_LEVEL': 0x8c,
            'REGISTER_CH1_LEVEL': 0x8e,
            'REGISTER_CH2_LEVEL': 0x90,
            'REGISTER_CH3_LEVEL': 0x92,
            'REGISTER_CH4_LEVEL': 0x94,
            'REGISTER_CH5_LEVEL': 0x96,
            'REGISTER_CH6_LEVEL': 0x98,
            'REGISTER_CH7_LEVEL': 0x9a,
            'REGISTER_CHANNEL': 0x82,
            'REGISTER_CHANNELS_END': 0x9c,
            'REGISTER_CHANNELS_START': 0x8c,
            'REGISTER_COMMAND': 0x89,
            'REGISTER_COMMAND_STATUS': 0x8b,
            'REGISTER_END_ADDR': 0xcb,
            'REGISTER_FADE_IN_TIME': 0x9e,
            'REGISTER_FREQUENCY': 0xb8,
            'REGISTER_FROM_LEVEL': 0x80,
            'REGISTER_INT_TEMP': 0xbc,
            'REGISTER_INT_TEMP_CAL': 0xad,
            'REGISTER_INT_VREF11': 0xac,
            'REGISTER_MAX_TEMP': 0x9d,
            'REGISTER_METRICS_INT': 0xb0,
            'REGISTER_MIN_OFF_TIME_TICKS': 0xa6,
            'REGISTER_MIN_ON_TIME_TICKS': 0xa4,
            'REGISTER_NTC_TEMP': 0xbe,
            'REGISTER_NTC_TEMP_OFS': 0xaf,
            'REGISTER_OPTIONS': 0x9c,
            'REGISTER_RAM': 0xc2,
            'REGISTER_RANGE_BEGIN': 0xa8,
            'REGISTER_RANGE_DIVIDER': 0xaa,
            'REGISTER_READ_LENGTH': 0x8a,
            'REGISTER_START_ADDR': 0x80,
            'REGISTER_SWITCH_ON_COUNT': 0xb4,
            'REGISTER_SWITCH_ON_MIN_TIME': 0xb2,
            'REGISTER_TIME': 0x85,
            'REGISTER_TO_LEVEL': 0x83,
            'REGISTER_VCC': 0xc0,
            'REGISTER_VERSION': 0xb9,
            'REGISTER_ZC_DELAY_TICKS': 0xa2,

            'I2C': type('obj', (object,), {'ADDRESS': 23})(),
            'REGISTER': type('obj', (object,), {'START_ADDR': 128, 'FROM_LEVEL': 128, 'CHANNEL': 130, 'TO_LEVEL': 131, 'TIME': 133, 'COMMAND': 137, 'READ_LENGTH': 138, 'COMMAND_STATUS': 139, 'CHANNELS_START': 140, 'CH0_LEVEL': 140, 'CH1_LEVEL': 142, 'CH2_LEVEL': 144, 'CH3_LEVEL': 146, 'CH4_LEVEL': 148, 'CH5_LEVEL': 150, 'CH6_LEVEL': 152, 'CH7_LEVEL': 154, 'CHANNELS_END': 156, 'FREQUENCY': 184, 'INT_TEMP': 188, 'NTC_TEMP': 190, 'VCC': 192, 'RAM': 194, 'OPTIONS': 156, 'MAX_TEMP': 157, 'FADE_IN_TIME': 158, 'ZC_DELAY_TICKS': 162, 'MIN_ON_TIME_TICKS': 164, 'MIN_OFF_TIME_TICKS': 166, 'RANGE_BEGIN': 168, 'RANGE_DIVIDER': 170, 'INT_VREF11': 172, 'INT_TEMP_CAL': 173, 'NTC_TEMP_OFS': 175, 'METRICS_INT': 176, 'ADJ_HW_CYCLES': 177, 'SWITCH_ON_MIN_TIME': 178, 'SWITCH_ON_COUNT': 180, 'ADDRESS': 202, 'END_ADDR': 203, 'VERSION': 185})(),
            'EVENT': type('obj', (object,), {'METRICS_REPORT': 240, 'TEMPERATURE_ALERT': 241, 'FADING_COMPLETE': 242, 'EEPROM_WRITTEN': 243, 'FREQUENCY_WARNING': 244, 'CHANNEL_ON_OFF': 245, 'SYNC_EVENT': 246})(),
            'COMMAND': type('obj', (object,), {'SET_LEVEL': 16, 'FADE': 17, 'READ_CHANNELS': 18, 'READ_NTC': 32, 'READ_INT_TEMP': 33, 'READ_VCC': 34, 'READ_AC_FREQUENCY': 35, 'WRITE_EEPROM': 80, 'RESTORE_FS': 81, 'GET_TIMER_TICKS': 82, 'PRINT_INFO': 83, 'FORCE_TEMP_CHECK': 84, 'PRINT_METRICS': 85, 'SET_MODE': 86, 'ZC_TIMINGS_OUTPUT': 96, 'PRINT_CONFIG': 145, 'WRITE_CONFIG': 146, 'WRITE_EEPROM_NOW': 147, 'MEASURE_FREQ': 148, 'INIT_EEPROM': 149, 'INCR_ZC_DELAY': 130, 'DECR_ZC_DELAY': 131, 'SET_ZC_DELAY': 132, 'INCR_HW_TICKS': 133, 'DECR_HW_TICKS': 134, 'SET_ZC_SYNC': 236, 'DUMP_CHANNELS': 237, 'DUMP_MEM': 238, 'STATUS_OK': 0, 'STATUS_ERROR': 255})(),
            'OPTIONS': type('obj', (object,), {'RESTORE_LEVEL': 1, 'MODE_LEADING_EDGE': 2, 'TEMP_ALERT_TRIGGERED': 4, 'NEGATIVE_ZC_DELAY': 8})(),
            'EEPROM_FLAGS': type('obj', (object,), {'CONFIG_UPDATED': 1})(),
        }
